name: Solana Contract Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Solana CLI
        run: curl --proto '=https' --tlsv1.2 -sSfL https://raw.githubusercontent.com/solana-developers/solana-install/main/install.sh | bash -s - v1.9.6

      - name: Install Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: yarn install

      - name: Build the Smart Contracts
        run: anchor build

      - name: Start Solana Local Validator
        run: solana-test-validator --reset &
        timeout-minutes: 2

      - name: Deploy the Smart Contracts
        run: anchor deploy

      - name: Run Tests
        run: anchor test
