name: Solana Contract Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Solana CLI
        run: |
          curl --proto '=https' --tlsv1.2 -sSfL https://raw.githubusercontent.com/solana-developers/solana-install/main/install.sh | bash -s - v1.18.13
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          solana --version

      - name: Install Rust and Cargo Dependencies
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
          rustup install stable
          rustup default stable
          rustup target add bpfel-unknown-unknown
          rustup component add rust-src
          cargo install --git https://github.com/anza-xyz/cargo-build-sbf.git cargo-build-sbf
          cargo --version
          rustc --version
          cargo build-sbf --help

      - name: Install Anchor CLI
        run: |
          cargo install --git https://github.com/coral-xyz/anchor avm --force --locked
          avm install latest
          avm use latest
          anchor --version

      - name: Install Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: yarn install

      - name: Build the Smart Contracts
        run: anchor build

      - name: Start Solana Local Validator
        run: solana-test-validator --reset &
        timeout-minutes: 2

      - name: Deploy the Smart Contracts
        run: anchor deploy

      - name: Run Tests
        run: anchor test
