name: Solana Program CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Solana, Anchor, and Rust
        uses: solana-developers/github-actions/setup-all@v1
        with:
          solana_version: "1.18.13"
          anchor_version: "0.30.1"
          node_version: "18"

      - name: Extract Versions
        id: versions
        uses: solana-developers/github-actions/extract-versions@v1

      - name: Build & Verify Smart Contract
        uses: solana-developers/github-actions/build-verified@v1
        with:
          program: "solana_contracts"

      - name: Start Solana Local Validator
        run: solana-test-validator --reset &
        timeout-minutes: 2

      - name: Deploy to Devnet
        if: github.ref == 'refs/heads/main'
        uses: solana-developers/github-actions/write-program-buffer@v1
        with:
          program-id: "G3fCSLaKAw8LQAoVoPEGzaJ7PMD33dno3TUU647qcXAc"
          program: "solana_contracts"
          rpc-url: ${{ secrets.DEVNET_SOLANA_DEPLOY_URL }}
          keypair: ${{ secrets.DEVNET_DEPLOYER_KEYPAIR }}
          priority-fee: 0

      - name: Run Tests
        run: anchor test
